language: node_js
node_js:
  - 12.13.0
dist: xenial
services:
  - xvfb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
cache: yarn
install:
    - yarn install
script:
    - yarn dev
