language: node_js
node_js:
  - 12.13.0
dist: xenial
addons:
  chrome: stable
services:
  - xvfb
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 https://chromium.org &
cache: yarn
install:
    - yarn install
script:
    - yarn dev

